### PR TITLE
added client.sh

### LINKED ISSUE #26: Automate testing
In order to help with testing, create the file `client/Vagrantfile` that starts automatically a client VirtualBox machine, with no disks, with bridged networking, that boots from the network. This may help a bit the testing process.

Maybe it can be done more easily with a shell script, like `client.sh`, which uses `virtualbox` commands and options.

By the way, where is the documentation of the virtualbox command-line options?

### PR DESCRIPTION
**Pull request by d78ui98**
added client.sh it allows to create ltsp clients and can poweroff reset and pause them

closes #26

### CODE REVIEW

**Comment by dashohoxha** [comment]
- How would you describe its usage to the users? Can you write a `usage()` function?
 - It seems to me that it is becoming a bit complex. It might be easier with a `client/Vagrantfile`.
 - What editor are you using? Please try to use an editor that helps with automatic indentation (and code coloring, etc.). Even `geany` could be bettter (if you can't use Emacs).

**Comment by d78ui98** [comment]
- yes I can write a `usage()` function
- Okay I will try with the `Vagrantfile`
- I am using `sublime`. I will try `geany`

**Comment by dashohoxha** [comment]
> I am using sublime.

I have never used `sublime` but I am surprised that it cannot handle bash code correctly.

**Comment by dashohoxha** [comment]
I am merging this one too, but you should continue to work on the client and on testing the LTSP server.

**Pull request merged**
