### PR TITLE
Creating virtual network for communication

### LINKED ISSUE #44: Create a virtual network for communication of all LTSP client, server and dhcp server
When you test with a virtual client and a virtual DHCP server (and virtual LTSP server of course), and all three of them are on the same computer/laptop, I think that you may need to create a virtual network as well, and connect all three of them to this virtual network, so that they can communicate with each-other.

If you bridge all three of them to an ethernet (cable) network interface, this can work only if this interface is connected to a switch/hub (or to another computer) through a cable. If no cable is connected, then the status of the network interface will be NO-CARRIER (not connected), and the same status will be inherited to the virtual interfaces that are bridged over it (ltsp-client, dhcp-server, ltsp-server), and so all three of them will be disconnected from each-other.

However it is not very practical to connect the machine to a hub just to test the ltsp-client and ltsp-server, so it may be better to create and use a virtual network in this case.
Maybe you can create a script `test.sh start` which creates the virtual interface and modifies settings.sh by setting which interface to use for bridging to LAN. Then you can start up the dhcp-server, ltsp-server, ltsp-client and perform the testing steps (make login on the client, etc.)
When you are done, you call `test.sh stop` which shuts down the virtual machines, deletes the virtual interface, then modifies back `settings.sh`.

This shows that the interface (on the laptop) that will be used for bridging to LAN cannot be auto-detected, in general. In some special cases you may be able to auto-detect it, but not always. For example, in the mode non-standalone, you may look for the default route, find the interface, and that is the one that you should use for bridging to LAN. But this assumes that the laptop is already connected to the LAN and has received an IP from the DHCP server, and it is not connected to any wifi networks). So, it may not always work.

In standalone mode however, you can use this method to get the WAN interface and it will always work correctly

### PR DESCRIPTION
**Pull request by d78ui98**
- [x] adding host-only config to `Vagrantfile`
- [x] update `client.sh` to use host-only adapter 
- [x] update `install.sh` accordingly
- [x] update `settings.sh` accordingly

closes #44

### CODE REVIEW

**Comment by akash0x53** [comment]
Issue #44 is related to testing (taken from https://github.com/docker-scripts/dev--LTSP/issues/18#issuecomment-394091925). With this PR ltsp client will never be able to communicate with ltsp server because of "host-only" network used. Please revert these changes and keep it for testing purpose in separate directory. Closing this PR as it's not valid.

**Comment by d78ui98** [comment]
> Please revert these changes and keep it for testing purpose in separate directory

Okay. I understand it will not work in the real world. It is only for testing. Will create a seperate directory for this.

**Comment by dashohoxha** [comment]
>  I understand it will not work in the real world. It is only for testing. Will create a seperate directory for this.

Why not use if..then..else, instead of creating 2 different copies, one for testing and one for real?

**Comment by dashohoxha** [comment]
> Why not use if..then..else, instead of creating 2 different copies, one for testing and one for real?

I mean, we want to test the scripts themselves. If we keep 2 different copies of them, then we will have to synchronize these 2 copies whenever we change one of them. This is too bad.

**Comment by d78ui98** [comment]
very good idea.

**Pull request closed without merging**
