### PR TITLE
updated readme file

### LINKED ISSUE #94: update readme file on buster branch
Readme file should be updated with the most compact and to the point instructions.

### PR DESCRIPTION
**Pull request by d78ui98**
closes #94

### CODE REVIEW

**Comment by d78ui98** [comment]
Please let me know your thoughts on this. 

Also, I was thinking we should also opt for the new naming convention of ltsp by alkis. I showed a friend who is very experienced in ltsp. He suggested this.

Normal mode can be proxy dhcp mode or chrootless ltsp.

**Comment by dashohoxha** [comment]
> Normal mode can be proxy dhcp mode or chrootless ltsp.

Can you explain to me what `chrootless` is? Because I don't know what it means, and I am sure that a normal user (or a teacher) does not know what it means.

**Comment by d78ui98** [comment]
chrootless is the ltsp pnp. It is just another name for it. - http://wiki.ltsp.org/wiki/Installation/Ubuntu#B.29_Installing_LTSP_in_.22chrootless.22_.28previously_pnp.29_mode

**Comment by dashohoxha** [comment]
> chrootless is the ltsp pnp

This does not explain what `chrootless` is (to a beginner like me), because the question becomes: What is `ltsp pnp`?

**Comment by d78ui98** [comment]
okay. Before `chrootless`. We should know what is chroot. 
In one of the ltsp setup client boots from the chroot from `/opt/ltsp/arch/`. An ltsp server can have multiple choots to boot from.

A more simpler setup is ltsp-pnp. This does not involve `chroot`. There is a single img from which clients boot. No chroot hence chrootless.

**Comment by d78ui98** [comment]
But in virtual ltsp server we are using ltsp-pnp only. So I just want to add something to normal mode.
normal mode to just normal mode(proxy dhcp)

should we do this?

**Pull request merged**
